[package]
name = "tagger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.15"
eyre = "0.6.8"
scan_dir = "0.3.3"

infer = "0.9.0"
metaflac = "0.2.5"
mp4ameta = "0.11.0"
id3 = "1.3.0"
