pipeline:
  build:
    image: messense/rust-musl-cross:${IMAGE}
    commands:
      - cargo build --release --target=${PLATFORM}
      - musl-strip target/${PLATFORM}/release/tagger
      - mv target/${PLATFORM}/release/tagger target/tagger-${PLATFORM}
  deploy: 
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_token
      base_url: https://codeberg.org
      files: target/tagger-${PLATFORM}

matrix:
  include:
    - PLATFORM: aarch64-unknown-linux-musl
      IMAGE: aarch64-musl
    - PLATFORM: i686-unknown-linux-musl
      IMAGE: i686-musl
    - PLATFORM: x86_64-unknown-linux-musl
      IMAGE: x86_64-musl
    - PLATFORM: x86_64-unknown-linux-musl
      IMAGE: x86_64-musl
    # - x86_64-apple-darwin
    # - x86_64-pc-windows-gnu

depends_on:
  - lint

when:
  event: tag
  branches: main
